export interface FoodSuggestion {
  name: string;
  category: string;
}

export const FOOD_SUGGESTIONS: FoodSuggestion[] = [
  // Produce
  { name: "Apples", category: "Produce" },
  { name: "Bananas", category: "Produce" },
  { name: "Oranges", category: "Produce" },
  { name: "Lemons", category: "Produce" },
  { name: "Limes", category: "Produce" },
  { name: "Grapes", category: "Produce" },
  { name: "Strawberries", category: "Produce" },
  { name: "Blueberries", category: "Produce" },
  { name: "Raspberries", category: "Produce" },
  { name: "Blackberries", category: "Produce" },
  { name: "Watermelon", category: "Produce" },
  { name: "Mango", category: "Produce" },
  { name: "Pineapple", category: "Produce" },
  { name: "Peaches", category: "Produce" },
  { name: "Pears", category: "Produce" },
  { name: "Plums", category: "Produce" },
  { name: "Cherries", category: "Produce" },
  { name: "Avocado", category: "Produce" },
  { name: "Tomatoes", category: "Produce" },
  { name: "Cherry Tomatoes", category: "Produce" },
  { name: "Roma Tomatoes", category: "Produce" },
  { name: "Potatoes", category: "Produce" },
  { name: "Sweet Potatoes", category: "Produce" },
  { name: "Yams", category: "Produce" },
  { name: "Onions", category: "Produce" },
  { name: "Red Onions", category: "Produce" },
  { name: "Green Onions", category: "Produce" },
  { name: "Shallots", category: "Produce" },
  { name: "Garlic", category: "Produce" },
  { name: "Carrots", category: "Produce" },
  { name: "Baby Carrots", category: "Produce" },
  { name: "Broccoli", category: "Produce" },
  { name: "Cauliflower", category: "Produce" },
  { name: "Spinach", category: "Produce" },
  { name: "Baby Spinach", category: "Produce" },
  { name: "Kale", category: "Produce" },
  { name: "Arugula", category: "Produce" },
  { name: "Romaine Lettuce", category: "Produce" },
  { name: "Iceberg Lettuce", category: "Produce" },
  { name: "Mixed Greens", category: "Produce" },
  { name: "Cucumber", category: "Produce" },
  { name: "Bell Peppers", category: "Produce" },
  { name: "Jalapeños", category: "Produce" },
  { name: "Serrano Peppers", category: "Produce" },
  { name: "Zucchini", category: "Produce" },
  { name: "Yellow Squash", category: "Produce" },
  { name: "Butternut Squash", category: "Produce" },
  { name: "Acorn Squash", category: "Produce" },
  { name: "Mushrooms", category: "Produce" },
  { name: "Baby Bella Mushrooms", category: "Produce" },
  { name: "Portobello Mushrooms", category: "Produce" },
  { name: "Celery", category: "Produce" },
  { name: "Corn", category: "Produce" },
  { name: "Asparagus", category: "Produce" },
  { name: "Green Beans", category: "Produce" },
  { name: "Snap Peas", category: "Produce" },
  { name: "Snow Peas", category: "Produce" },
  { name: "Edamame", category: "Produce" },
  { name: "Beets", category: "Produce" },
  { name: "Radishes", category: "Produce" },
  { name: "Turnips", category: "Produce" },
  { name: "Cabbage", category: "Produce" },
  { name: "Bok Choy", category: "Produce" },
  { name: "Brussels Sprouts", category: "Produce" },
  { name: "Artichoke", category: "Produce" },
  { name: "Eggplant", category: "Produce" },
  { name: "Leeks", category: "Produce" },
  { name: "Fennel", category: "Produce" },
  { name: "Okra", category: "Produce" },
  { name: "Plantains", category: "Produce" },
  { name: "Ginger Root", category: "Produce" },
  { name: "Fresh Basil", category: "Produce" },
  { name: "Fresh Cilantro", category: "Produce" },
  { name: "Fresh Parsley", category: "Produce" },
  { name: "Fresh Mint", category: "Produce" },
  { name: "Fresh Rosemary", category: "Produce" },
  { name: "Fresh Thyme", category: "Produce" },
  { name: "Fresh Dill", category: "Produce" },
  { name: "Scallions", category: "Produce" },

  // Meat & Seafood
  { name: "Chicken Breast", category: "Meat & Seafood" },
  { name: "Chicken Thighs", category: "Meat & Seafood" },
  { name: "Chicken Wings", category: "Meat & Seafood" },
  { name: "Whole Chicken", category: "Meat & Seafood" },
  { name: "Ground Beef", category: "Meat & Seafood" },
  { name: "Ground Turkey", category: "Meat & Seafood" },
  { name: "Ground Pork", category: "Meat & Seafood" },
  { name: "Sirloin Steak", category: "Meat & Seafood" },
  { name: "Ribeye Steak", category: "Meat & Seafood" },
  { name: "Flank Steak", category: "Meat & Seafood" },
  { name: "Skirt Steak", category: "Meat & Seafood" },
  { name: "Chuck Roast", category: "Meat & Seafood" },
  { name: "Beef Brisket", category: "Meat & Seafood" },
  { name: "Pork Chops", category: "Meat & Seafood" },
  { name: "Pork Tenderloin", category: "Meat & Seafood" },
  { name: "Pork Ribs", category: "Meat & Seafood" },
  { name: "Bacon", category: "Meat & Seafood" },
  { name: "Canadian Bacon", category: "Meat & Seafood" },
  { name: "Ham", category: "Meat & Seafood" },
  { name: "Turkey Breast", category: "Meat & Seafood" },
  { name: "Lamb Chops", category: "Meat & Seafood" },
  { name: "Lamb Shoulder", category: "Meat & Seafood" },
  { name: "Salmon Fillet", category: "Meat & Seafood" },
  { name: "Tuna Steak", category: "Meat & Seafood" },
  { name: "Tilapia", category: "Meat & Seafood" },
  { name: "Cod", category: "Meat & Seafood" },
  { name: "Halibut", category: "Meat & Seafood" },
  { name: "Mahi Mahi", category: "Meat & Seafood" },
  { name: "Catfish", category: "Meat & Seafood" },
  { name: "Trout", category: "Meat & Seafood" },
  { name: "Shrimp", category: "Meat & Seafood" },
  { name: "Scallops", category: "Meat & Seafood" },
  { name: "Crab Legs", category: "Meat & Seafood" },
  { name: "Lobster Tail", category: "Meat & Seafood" },
  { name: "Clams", category: "Meat & Seafood" },
  { name: "Mussels", category: "Meat & Seafood" },
  { name: "Pepperoni", category: "Meat & Seafood" },
  { name: "Salami", category: "Meat & Seafood" },
  { name: "Prosciutto", category: "Meat & Seafood" },
  { name: "Chorizo", category: "Meat & Seafood" },
  { name: "Italian Sausage", category: "Meat & Seafood" },
  { name: "Kielbasa", category: "Meat & Seafood" },
  { name: "Hot Dogs", category: "Meat & Seafood" },
  { name: "Deli Turkey", category: "Meat & Seafood" },
  { name: "Deli Ham", category: "Meat & Seafood" },

  // Dairy & Eggs
  { name: "Whole Milk", category: "Dairy & Eggs" },
  { name: "2% Milk", category: "Dairy & Eggs" },
  { name: "Skim Milk", category: "Dairy & Eggs" },
  { name: "Almond Milk", category: "Dairy & Eggs" },
  { name: "Oat Milk", category: "Dairy & Eggs" },
  { name: "Soy Milk", category: "Dairy & Eggs" },
  { name: "Eggs", category: "Dairy & Eggs" },
  { name: "Egg Whites", category: "Dairy & Eggs" },
  { name: "Butter", category: "Dairy & Eggs" },
  { name: "Unsalted Butter", category: "Dairy & Eggs" },
  { name: "Cheddar Cheese", category: "Dairy & Eggs" },
  { name: "Mozzarella Cheese", category: "Dairy & Eggs" },
  { name: "Parmesan Cheese", category: "Dairy & Eggs" },
  { name: "Feta Cheese", category: "Dairy & Eggs" },
  { name: "Swiss Cheese", category: "Dairy & Eggs" },
  { name: "Gouda Cheese", category: "Dairy & Eggs" },
  { name: "Brie Cheese", category: "Dairy & Eggs" },
  { name: "Goat Cheese", category: "Dairy & Eggs" },
  { name: "Provolone Cheese", category: "Dairy & Eggs" },
  { name: "Colby Jack Cheese", category: "Dairy & Eggs" },
  { name: "Pepper Jack Cheese", category: "Dairy & Eggs" },
  { name: "Cream Cheese", category: "Dairy & Eggs" },
  { name: "Sour Cream", category: "Dairy & Eggs" },
  { name: "Greek Yogurt", category: "Dairy & Eggs" },
  { name: "Plain Yogurt", category: "Dairy & Eggs" },
  { name: "Cottage Cheese", category: "Dairy & Eggs" },
  { name: "Ricotta Cheese", category: "Dairy & Eggs" },
  { name: "Heavy Cream", category: "Dairy & Eggs" },
  { name: "Half and Half", category: "Dairy & Eggs" },
  { name: "Whipped Cream", category: "Dairy & Eggs" },
  { name: "Kefir", category: "Dairy & Eggs" },
  { name: "Ghee", category: "Dairy & Eggs" },
  { name: "Buttermilk", category: "Dairy & Eggs" },

  // Grains & Bread
  { name: "White Bread", category: "Grains & Bread" },
  { name: "Whole Wheat Bread", category: "Grains & Bread" },
  { name: "Sourdough Bread", category: "Grains & Bread" },
  { name: "Multigrain Bread", category: "Grains & Bread" },
  { name: "Rye Bread", category: "Grains & Bread" },
  { name: "Bagels", category: "Grains & Bread" },
  { name: "English Muffins", category: "Grains & Bread" },
  { name: "Pita Bread", category: "Grains & Bread" },
  { name: "Flour Tortillas", category: "Grains & Bread" },
  { name: "Corn Tortillas", category: "Grains & Bread" },
  { name: "Hamburger Buns", category: "Grains & Bread" },
  { name: "Hot Dog Buns", category: "Grains & Bread" },
  { name: "Dinner Rolls", category: "Grains & Bread" },
  { name: "White Rice", category: "Grains & Bread" },
  { name: "Brown Rice", category: "Grains & Bread" },
  { name: "Basmati Rice", category: "Grains & Bread" },
  { name: "Jasmine Rice", category: "Grains & Bread" },
  { name: "Wild Rice", category: "Grains & Bread" },
  { name: "Spaghetti", category: "Grains & Bread" },
  { name: "Penne Pasta", category: "Grains & Bread" },
  { name: "Fettuccine", category: "Grains & Bread" },
  { name: "Rotini Pasta", category: "Grains & Bread" },
  { name: "Elbow Macaroni", category: "Grains & Bread" },
  { name: "Lasagna Noodles", category: "Grains & Bread" },
  { name: "Ramen Noodles", category: "Grains & Bread" },
  { name: "Rice Noodles", category: "Grains & Bread" },
  { name: "Oatmeal", category: "Grains & Bread" },
  { name: "Rolled Oats", category: "Grains & Bread" },
  { name: "Quinoa", category: "Grains & Bread" },
  { name: "Barley", category: "Grains & Bread" },
  { name: "Farro", category: "Grains & Bread" },
  { name: "Couscous", category: "Grains & Bread" },
  { name: "Polenta", category: "Grains & Bread" },
  { name: "Cornmeal", category: "Grains & Bread" },
  { name: "All-Purpose Flour", category: "Grains & Bread" },
  { name: "Whole Wheat Flour", category: "Grains & Bread" },
  { name: "Bread Flour", category: "Grains & Bread" },
  { name: "Granola", category: "Grains & Bread" },
  { name: "Breadcrumbs", category: "Grains & Bread" },
  { name: "Panko Breadcrumbs", category: "Grains & Bread" },
  { name: "Crackers", category: "Grains & Bread" },
  { name: "Rice Cakes", category: "Grains & Bread" },

  // Bakery
  { name: "Chocolate Chip Cookies", category: "Bakery" },
  { name: "Sugar Cookies", category: "Bakery" },
  { name: "Croissants", category: "Bakery" },
  { name: "Donuts", category: "Bakery" },
  { name: "Blueberry Muffins", category: "Bakery" },
  { name: "Bran Muffins", category: "Bakery" },
  { name: "Banana Bread", category: "Bakery" },
  { name: "Zucchini Bread", category: "Bakery" },
  { name: "Cinnamon Rolls", category: "Bakery" },
  { name: "Brownies", category: "Bakery" },
  { name: "Pound Cake", category: "Bakery" },
  { name: "Cheesecake", category: "Bakery" },
  { name: "Pie Crust", category: "Bakery" },
  { name: "Danish Pastry", category: "Bakery" },
  { name: "Scones", category: "Bakery" },
  { name: "Baguette", category: "Bakery" },

  // Canned Goods
  { name: "Diced Tomatoes", category: "Canned Goods" },
  { name: "Crushed Tomatoes", category: "Canned Goods" },
  { name: "Tomato Sauce", category: "Canned Goods" },
  { name: "Tomato Paste", category: "Canned Goods" },
  { name: "Whole Peeled Tomatoes", category: "Canned Goods" },
  { name: "Chicken Broth", category: "Canned Goods" },
  { name: "Beef Broth", category: "Canned Goods" },
  { name: "Vegetable Broth", category: "Canned Goods" },
  { name: "Black Beans", category: "Canned Goods" },
  { name: "Kidney Beans", category: "Canned Goods" },
  { name: "Chickpeas", category: "Canned Goods" },
  { name: "Pinto Beans", category: "Canned Goods" },
  { name: "White Beans", category: "Canned Goods" },
  { name: "Lentils", category: "Canned Goods" },
  { name: "Canned Corn", category: "Canned Goods" },
  { name: "Canned Green Beans", category: "Canned Goods" },
  { name: "Canned Peas", category: "Canned Goods" },
  { name: "Canned Tuna", category: "Canned Goods" },
  { name: "Canned Salmon", category: "Canned Goods" },
  { name: "Canned Sardines", category: "Canned Goods" },
  { name: "Coconut Milk", category: "Canned Goods" },
  { name: "Cream of Mushroom Soup", category: "Canned Goods" },
  { name: "Chicken Noodle Soup", category: "Canned Goods" },
  { name: "Tomato Soup", category: "Canned Goods" },
  { name: "Pumpkin Puree", category: "Canned Goods" },
  { name: "Condensed Milk", category: "Canned Goods" },
  { name: "Evaporated Milk", category: "Canned Goods" },
  { name: "Artichoke Hearts", category: "Canned Goods" },
  { name: "Olives", category: "Canned Goods" },
  { name: "Roasted Red Peppers", category: "Canned Goods" },

  // Condiments & Sauces
  { name: "Ketchup", category: "Condiments & Sauces" },
  { name: "Yellow Mustard", category: "Condiments & Sauces" },
  { name: "Dijon Mustard", category: "Condiments & Sauces" },
  { name: "Whole Grain Mustard", category: "Condiments & Sauces" },
  { name: "Mayonnaise", category: "Condiments & Sauces" },
  { name: "Ranch Dressing", category: "Condiments & Sauces" },
  { name: "Italian Dressing", category: "Condiments & Sauces" },
  { name: "Caesar Dressing", category: "Condiments & Sauces" },
  { name: "Balsamic Vinaigrette", category: "Condiments & Sauces" },
  { name: "Hot Sauce", category: "Condiments & Sauces" },
  { name: "Sriracha", category: "Condiments & Sauces" },
  { name: "Soy Sauce", category: "Condiments & Sauces" },
  { name: "Worcestershire Sauce", category: "Condiments & Sauces" },
  { name: "Teriyaki Sauce", category: "Condiments & Sauces" },
  { name: "Barbecue Sauce", category: "Condiments & Sauces" },
  { name: "Hoisin Sauce", category: "Condiments & Sauces" },
  { name: "Fish Sauce", category: "Condiments & Sauces" },
  { name: "Oyster Sauce", category: "Condiments & Sauces" },
  { name: "Tahini", category: "Condiments & Sauces" },
  { name: "Pesto", category: "Condiments & Sauces" },
  { name: "Marinara Sauce", category: "Condiments & Sauces" },
  { name: "Salsa", category: "Condiments & Sauces" },
  { name: "Guacamole", category: "Condiments & Sauces" },
  { name: "Hummus", category: "Condiments & Sauces" },
  { name: "Relish", category: "Condiments & Sauces" },
  { name: "Capers", category: "Condiments & Sauces" },
  { name: "Apple Cider Vinegar", category: "Condiments & Sauces" },
  { name: "White Wine Vinegar", category: "Condiments & Sauces" },
  { name: "Red Wine Vinegar", category: "Condiments & Sauces" },
  { name: "Balsamic Vinegar", category: "Condiments & Sauces" },
  { name: "Buffalo Sauce", category: "Condiments & Sauces" },
  { name: "Sweet Chili Sauce", category: "Condiments & Sauces" },
  { name: "Pickles", category: "Condiments & Sauces" },

  // Pantry
  { name: "Olive Oil", category: "Pantry" },
  { name: "Extra Virgin Olive Oil", category: "Pantry" },
  { name: "Vegetable Oil", category: "Pantry" },
  { name: "Canola Oil", category: "Pantry" },
  { name: "Coconut Oil", category: "Pantry" },
  { name: "Sesame Oil", category: "Pantry" },
  { name: "Avocado Oil", category: "Pantry" },
  { name: "Grapeseed Oil", category: "Pantry" },
  { name: "White Granulated Sugar", category: "Pantry" },
  { name: "Brown Sugar", category: "Pantry" },
  { name: "Powdered Sugar", category: "Pantry" },
  { name: "Honey", category: "Pantry" },
  { name: "Maple Syrup", category: "Pantry" },
  { name: "Agave Nectar", category: "Pantry" },
  { name: "Vanilla Extract", category: "Pantry" },
  { name: "Baking Soda", category: "Pantry" },
  { name: "Baking Powder", category: "Pantry" },
  { name: "Active Dry Yeast", category: "Pantry" },
  { name: "Cornstarch", category: "Pantry" },
  { name: "Cocoa Powder", category: "Pantry" },
  { name: "Salt", category: "Pantry" },
  { name: "Black Pepper", category: "Pantry" },
  { name: "Cumin", category: "Pantry" },
  { name: "Paprika", category: "Pantry" },
  { name: "Smoked Paprika", category: "Pantry" },
  { name: "Turmeric", category: "Pantry" },
  { name: "Oregano", category: "Pantry" },
  { name: "Thyme", category: "Pantry" },
  { name: "Rosemary", category: "Pantry" },
  { name: "Basil", category: "Pantry" },
  { name: "Cinnamon", category: "Pantry" },
  { name: "Cayenne Pepper", category: "Pantry" },
  { name: "Chili Powder", category: "Pantry" },
  { name: "Garlic Powder", category: "Pantry" },
  { name: "Onion Powder", category: "Pantry" },
  { name: "Italian Seasoning", category: "Pantry" },
  { name: "Red Pepper Flakes", category: "Pantry" },
  { name: "Bay Leaves", category: "Pantry" },
  { name: "Curry Powder", category: "Pantry" },
  { name: "Garam Masala", category: "Pantry" },
  { name: "Peanut Butter", category: "Pantry" },
  { name: "Almond Butter", category: "Pantry" },
  { name: "Cashew Butter", category: "Pantry" },
  { name: "Strawberry Jam", category: "Pantry" },
  { name: "Grape Jelly", category: "Pantry" },
  { name: "Raspberry Preserves", category: "Pantry" },
  { name: "Nutella", category: "Pantry" },
  { name: "Almonds", category: "Pantry" },
  { name: "Cashews", category: "Pantry" },
  { name: "Walnuts", category: "Pantry" },
  { name: "Pecans", category: "Pantry" },
  { name: "Pistachios", category: "Pantry" },
  { name: "Peanuts", category: "Pantry" },
  { name: "Mixed Nuts", category: "Pantry" },
  { name: "Sunflower Seeds", category: "Pantry" },
  { name: "Pumpkin Seeds", category: "Pantry" },
  { name: "Chia Seeds", category: "Pantry" },
  { name: "Flaxseeds", category: "Pantry" },
  { name: "Raisins", category: "Pantry" },
  { name: "Dried Cranberries", category: "Pantry" },
  { name: "Dried Apricots", category: "Pantry" },
  { name: "Chocolate Chips", category: "Pantry" },
  { name: "Lemon Juice", category: "Pantry" },

  // Snacks
  { name: "Potato Chips", category: "Snacks" },
  { name: "Tortilla Chips", category: "Snacks" },
  { name: "Popcorn", category: "Snacks" },
  { name: "Pretzels", category: "Snacks" },
  { name: "Pita Chips", category: "Snacks" },
  { name: "Beef Jerky", category: "Snacks" },
  { name: "Turkey Jerky", category: "Snacks" },
  { name: "Granola Bars", category: "Snacks" },
  { name: "Protein Bars", category: "Snacks" },
  { name: "Trail Mix", category: "Snacks" },
  { name: "Cheese Crackers", category: "Snacks" },
  { name: "Graham Crackers", category: "Snacks" },
  { name: "Animal Crackers", category: "Snacks" },
  { name: "Goldfish Crackers", category: "Snacks" },
  { name: "Veggie Straws", category: "Snacks" },
  { name: "Fruit Snacks", category: "Snacks" },
  { name: "Applesauce", category: "Snacks" },
  { name: "Dried Mango", category: "Snacks" },

  // Beverages
  { name: "Orange Juice", category: "Beverages" },
  { name: "Apple Juice", category: "Beverages" },
  { name: "Cranberry Juice", category: "Beverages" },
  { name: "Grape Juice", category: "Beverages" },
  { name: "Lemonade", category: "Beverages" },
  { name: "Sparkling Water", category: "Beverages" },
  { name: "Coconut Water", category: "Beverages" },
  { name: "Coffee Beans", category: "Beverages" },
  { name: "Ground Coffee", category: "Beverages" },
  { name: "Instant Coffee", category: "Beverages" },
  { name: "Cold Brew Coffee", category: "Beverages" },
  { name: "Green Tea", category: "Beverages" },
  { name: "Black Tea", category: "Beverages" },
  { name: "Herbal Tea", category: "Beverages" },
  { name: "Kombucha", category: "Beverages" },
  { name: "Sports Drink", category: "Beverages" },
  { name: "Protein Shake", category: "Beverages" },
  { name: "Electrolyte Drink", category: "Beverages" },
  { name: "Soda Water", category: "Beverages" },
  { name: "Tonic Water", category: "Beverages" },
  { name: "Red Wine", category: "Beverages" },
  { name: "White Wine", category: "Beverages" },
  { name: "Beer", category: "Beverages" },

  // Frozen
  { name: "Frozen Peas", category: "Frozen" },
  { name: "Frozen Corn", category: "Frozen" },
  { name: "Frozen Broccoli", category: "Frozen" },
  { name: "Frozen Spinach", category: "Frozen" },
  { name: "Frozen Mixed Vegetables", category: "Frozen" },
  { name: "Frozen Edamame", category: "Frozen" },
  { name: "Frozen Green Beans", category: "Frozen" },
  { name: "Frozen Strawberries", category: "Frozen" },
  { name: "Frozen Blueberries", category: "Frozen" },
  { name: "Frozen Mango Chunks", category: "Frozen" },
  { name: "Frozen Mixed Berries", category: "Frozen" },
  { name: "Frozen Pizza", category: "Frozen" },
  { name: "Frozen Waffles", category: "Frozen" },
  { name: "Frozen Burritos", category: "Frozen" },
  { name: "Frozen Shrimp", category: "Frozen" },
  { name: "Frozen Chicken Nuggets", category: "Frozen" },
  { name: "Frozen Fries", category: "Frozen" },
  { name: "Frozen Tater Tots", category: "Frozen" },
  { name: "Ice Cream", category: "Frozen" },

  // Desserts
  { name: "Dark Chocolate Bar", category: "Desserts" },
  { name: "Milk Chocolate Bar", category: "Desserts" },
  { name: "Gummy Bears", category: "Desserts" },
  { name: "Marshmallows", category: "Desserts" },
  { name: "Caramel Sauce", category: "Desserts" },
  { name: "Hot Fudge", category: "Desserts" },
  { name: "Pudding Mix", category: "Desserts" },
  { name: "Gelato", category: "Desserts" },
  { name: "Sorbet", category: "Desserts" },

  // Cleaning
  { name: "Dish Soap", category: "Cleaning" },
  { name: "Dishwasher Pods", category: "Cleaning" },
  { name: "Laundry Detergent", category: "Cleaning" },
  { name: "Dryer Sheets", category: "Cleaning" },
  { name: "Fabric Softener", category: "Cleaning" },
  { name: "All-Purpose Cleaner", category: "Cleaning" },
  { name: "Bleach", category: "Cleaning" },
  { name: "Disinfecting Wipes", category: "Cleaning" },
  { name: "Paper Towels", category: "Cleaning" },
  { name: "Toilet Paper", category: "Cleaning" },
  { name: "Trash Bags", category: "Cleaning" },
  { name: "Aluminum Foil", category: "Cleaning" },
  { name: "Plastic Wrap", category: "Cleaning" },
  { name: "Parchment Paper", category: "Cleaning" },
  { name: "Ziploc Bags", category: "Cleaning" },
  { name: "Sponges", category: "Cleaning" },
  { name: "Stain Remover", category: "Cleaning" },
  { name: "Glass Cleaner", category: "Cleaning" },

  // Personal Care
  { name: "Shampoo", category: "Personal Care" },
  { name: "Conditioner", category: "Personal Care" },
  { name: "Body Wash", category: "Personal Care" },
  { name: "Bar Soap", category: "Personal Care" },
  { name: "Hand Soap", category: "Personal Care" },
  { name: "Toothpaste", category: "Personal Care" },
  { name: "Mouthwash", category: "Personal Care" },
  { name: "Dental Floss", category: "Personal Care" },
  { name: "Toothbrush", category: "Personal Care" },
  { name: "Deodorant", category: "Personal Care" },
  { name: "Body Lotion", category: "Personal Care" },
  { name: "Face Wash", category: "Personal Care" },
  { name: "Moisturizer", category: "Personal Care" },
  { name: "Sunscreen", category: "Personal Care" },
  { name: "Lip Balm", category: "Personal Care" },
  { name: "Razor", category: "Personal Care" },
  { name: "Shaving Cream", category: "Personal Care" },
  { name: "Cotton Balls", category: "Personal Care" },
  { name: "Cotton Swabs", category: "Personal Care" },
  { name: "Band-Aids", category: "Personal Care" },
  { name: "Vitamins", category: "Personal Care" },
  { name: "Multivitamins", category: "Personal Care" },
  { name: "Vitamin D", category: "Personal Care" },
  { name: "Fish Oil", category: "Personal Care" },
];

export function searchFoodItems(query: string): FoodSuggestion[] {
  const q = query.toLowerCase().trim();
  if (q.length < 1) return [];

  const prefixMatches: FoodSuggestion[] = [];
  const substringMatches: FoodSuggestion[] = [];

  for (const item of FOOD_SUGGESTIONS) {
    const lower = item.name.toLowerCase();
    if (lower.startsWith(q)) {
      prefixMatches.push(item);
    } else if (lower.includes(q)) {
      substringMatches.push(item);
    }
  }

  return [...prefixMatches, ...substringMatches].slice(0, 6);
}
